import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/shared/lib/utils';
import Providers from '@/shared/context/global/provider';
import { Sarabun, Tajawal } from 'next/font/google';

const sarabun = Sarabun({
  subsets: ['latin'],
  variable: '--font-en',
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  fallback: ['system-ui', 'sans-serif'],
});

const tajawal = Tajawal({
  subsets: ['arabic'],
  variable: '--font-ar',
  display: 'swap',
  weight: ['200', '300', '400', '500', '700', '800', '900'],
  fallback: ['system-ui', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Rose App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={cn(
        'h-full',
        'antialiased',
        sarabun.variable,
        tajawal.variable
      )}
      suppressHydrationWarning
    >
      <body className="bg-ds-bg-subtle">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
