import type { Metadata } from 'next';
import '@/app/globals.css';
import { cn } from '@/shared/lib/utils';
import Providers from '@/shared/context/global/provider';
import { hasLocale, NextIntlClientProvider } from 'next-intl';

import { getMessages } from 'next-intl/server';

import { Sarabun, Tajawal } from 'next/font/google';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';

const sarabun = Sarabun({
  subsets: ['latin'],
  variable: '--font-en',
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  fallback: ['system-ui', 'sans-serif'],
});

const tajawal = Tajawal({
  subsets: ['arabic'],
  variable: '--font-ar',
  display: 'swap',
  weight: ['200', '300', '400', '500', '700', '800', '900'],
  fallback: ['system-ui', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Rose App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  const isArabic = locale === 'ar';

  return (
    <html
      lang={locale}
      dir={isArabic ? 'rtl' : 'ltr'}
      className={cn(
        'h-full',
        'antialiased',
        sarabun.variable,
        tajawal.variable
      )}
      suppressHydrationWarning
    >
      <body className={isArabic ? 'font-tajawal' : 'font-sarabun'}>
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
